#!/usr/bin/env bash
# This script parses /etc/passwd and displays username, user ID, and home directory.

while IFS=":" read -r username password uid gid info home shell
do
    echo "$username:$uid:$home"
done < /etc/passwd

