#!/usr/bin/env bash
# This script parses an Apache log file and displays the visitor IP and HTTP status code.

while IFS=":" read -r username password uid gid info home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

awk '{print $1, $9}' "$1"
